export const ACTION = {
  FETCH_CURRENT_ITEM: "FETCH_CURRENT_ITEM",
  SET_CURRENT_ITEM: "SET_CURRENT_ITEM",
  UPDATE_CURRENT_ITEM: 'UPDATE_CURRENT_ITEM',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  RESET_CURRENT_ITEM: 'RESET_CURRENT_ITEM'
};
